### ISSUE TITLE
关于如何使用动态加载的应用

### ISSUE THREAD

**Issue by slashchenxiaojun** [michaelliao/compiler#1]
你好~对于demo中动态加载的应用，请问UserProxy是如何实现“一个简单的JavaBean是否被用户修改过呢”这个功能？这个功能是不是可以实现当用户修改了JavaBean的文件就可以触发事件，如：用户在User中添加了一个新的属性age，然后UserProxy发现没有这个属性，就在数据库中添加这个字段，求解答，非常感谢

**Comment by michaelliao** [comment]
没有看懂你的问题

**Comment by slashchenxiaojun** [comment]
就是想请问UserProxy这个类是如何实现  “一个简单的JavaBean是否被用户修改过” 这个功能，比如我想要实现一个功能：如果我修改了一个pojo的代码，然后希望数据库会根据我修改的代码实时的修改数据库里面字段的属性，那么这个项目compiler，可以帮助我完成这个功能吗？？？？
