### ISSUE TITLE
能否将新构造的Class添加到当前JVM？

### ISSUE THREAD

**Issue by tzraeq** [michaelliao/compiler#3]
你好，代码运行非常完美。

我有一个问题，这样构造的Class，在使用Class.forName的时候会产生异常，请问您是否研究过将生成的Class增加到JVM中去，让Class.forName也可正常运行呢？

谢谢！

**Comment by michaelliao** [comment]
Class.forName(className)使用的是当前classloader，即系统classloader

需要用Class.forName(className, boolean initialize, ClassLoader loader)

但是，加载编译后class的classloader的引用已经被丢弃了
